/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/About`; params?: Router.UnknownInputParams; } | { pathname: `/components/Contact`; params?: Router.UnknownInputParams; } | { pathname: `/components/FloatingShapes`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/Hero`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThreeCanvas`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/About`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Contact`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FloatingShapes`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Hero`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ThreeCanvas`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/About${`?${string}` | `#${string}` | ''}` | `/components/Contact${`?${string}` | `#${string}` | ''}` | `/components/FloatingShapes${`?${string}` | `#${string}` | ''}` | `/components/Header${`?${string}` | `#${string}` | ''}` | `/components/Hero${`?${string}` | `#${string}` | ''}` | `/components/ThreeCanvas${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/About`; params?: Router.UnknownInputParams; } | { pathname: `/components/Contact`; params?: Router.UnknownInputParams; } | { pathname: `/components/FloatingShapes`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/Hero`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThreeCanvas`; params?: Router.UnknownInputParams; };
    }
  }
}
